services:
  - type: web
    name: crypto-intelligence-assistant
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: crypto_intelligence_db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: CRYPTOCOMPARE_API_KEY
        sync: false

databases:
  - name: crypto_intelligence_db
    databaseName: crypto_intelligence
    ipAllowList: []
    plan: free
